In [ ]:
Q1:
Write a Python Program to Add two Matrices?

In [3]:
#Ans1:
def Add_Matrices(a,b):
    print(f"Inputs: {a},{b}")
    if len(a) == len(b):
        final_matrix = []
        for i in range(len(a)):
            if len(a[i]) == len(b[i]):
                final_matrix.append([])
                for j in range(len(a[i])):
                    final_matrix[i].append(a[i][j]+b[i][j])
            else:
                print('For addition, Matrices must contains same no of rows and columns') 
    else:
        print('For addition, Matrices must contains same no of rows and columns')
    print(f'Output: {final_matrix}')

Add_Matrices([[1,5,3],[8,7,6],[7,5,0]],[[6,1,1],[3,7,15],[9,0,4]])

Inputs: [[1, 5, 3], [8, 7, 6], [7, 5, 0]],[[6, 1, 1], [3, 7, 15], [9, 0, 4]]
Output: [[7, 6, 4], [11, 14, 21], [16, 5, 4]]


In [5]:
#Ans1 Using Numpy
import numpy as np

def add_matrices():
    R1=int(input("Enter the number of rows of first matrix: "))
    C1=int(input("Enter the number of columns of first matrix: "))
    R2=int(input("Enter the number of rows of second matrix: "))
    C2=int(input("Enter the number of columns of second matrix: "))
    print(f"Enter the {R1*C1} entries for the first matrix, separated by space: ")
    entries1=list(map(int, input().split()))
    print(f"Enter the {R1*C1} entries for the second matrix, separated by space: ")
    entries2=list(map(int, input().split()))
    M1=np.array(entries1).reshape(R1,C1)
    print(f"M1={M1}")
    M2=np.array(entries2).reshape(R2,C2)
    print(f"M2={M2}")
    M3=M1+M2
    print(f"""The result of addition of matrices 
    {M1} 
    and 
    {M2} 
    is 
    {M3}""")
    
add_matrices()

Enter the number of rows of first matrix: 3
Enter the number of columns of first matrix: 3
Enter the number of rows of second matrix: 3
Enter the number of columns of second matrix: 3
Enter the 9 entries for the first matrix, separated by space: 
1 2 3 4 5 6 7 8 9
Enter the 9 entries for the second matrix, separated by space: 
9 8 4 3 1 6 4 7 9
M1=[[1 2 3]
 [4 5 6]
 [7 8 9]]
M2=[[9 8 4]
 [3 1 6]
 [4 7 9]]
The result of addition of matrices 
    [[1 2 3]
 [4 5 6]
 [7 8 9]] 
    and 
    [[9 8 4]
 [3 1 6]
 [4 7 9]] 
    is 
    [[10 10  7]
 [ 7  6 12]
 [11 15 18]]


In [ ]:
Q2:
Write a Python Program to Multiply two Matrices?

In [5]:
#Ans2:
def multiply_matrices(a,b):
    output = []
    if len(a[0]) == len(b):
        for k in range(len(a[0])):
            output.append([0 for k in range(len(b[0]))])
        for i in range(len(a)):
            for j in range(len(b[0])):
                for l in range(len(b)):
                    output[i][j] += a[i][l]*b[l][j]
        print(output)     
    else:
        print('Matrix Multiplication is Not Possible')
        
multiply_matrices([[1, 5, 3], [8, 7, 6], [7, 5, 0]],[[6, 1, 1], [3, 7, 15], [9, 0, 4]])

[[48, 36, 88], [123, 57, 137], [57, 42, 82]]


In [ ]:
Q3:
Write a Python Program to transpose a Matrix ?

In [8]:
#Ans3
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2],[4,5],[6,7]]
c = [[1,2,3],[4,5,6]]

def generate_transpose(matrix):
    matrix_new = []
    for item in range(len(matrix[0])):
        matrix_new.append([0 for i in range(len(matrix))])
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            matrix_new[j][i] = matrix[i][j]
    print(f'{matrix} ---> {matrix_new}')
        
generate_transpose(a)
generate_transpose(b)
generate_transpose(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] ---> [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 2], [4, 5], [6, 7]] ---> [[1, 4, 6], [2, 5, 7]]
[[1, 2, 3], [4, 5, 6]] ---> [[1, 4], [2, 5], [3, 6]]


In [ ]:
Q4:
Write a Python Program to sort Words in an Alphabatical Order ?

In [11]:
#Ans4:
def word_order():
    words=input("Enter a string of words: ").title()
    sorted_words=sorted(words.split())
    print(" ".join(sorted_words))
    
word_order()

Enter a string of words: ineuron is the best platform to learn Data Science
Best Data Ineuron Is Learn Platform Science The To


In [ ]:
Q5:
Write a Python Program to remove Punctuations From a String ?

In [18]:
#Ans5:
def Remove_Punc():
    MyString=input("Enter any string:\n")
    punctuation="""!()-[]{};:'"\,<>./?@#$%^&*_~"""
    Result=" "
    for item in MyString:
        if item not in punctuation:
            Result = Result+item
    print(f"Result is: {Result}")
        
Remove_Punc()

Enter any string:
I am learning D/S with the help of Sudhanshu & Krish
Result is:  I am learning DS with the help of Sudhanshu  Krish
